version: '3.5'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    command: sh -c "npm install &&  npm run start:dev"

    volumes:
      - ../:/app

  nest-db:
    image: postgres:14
    container_name: nest-db
    restart: always
    mem_limit: 1g
    environment:
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: nest-db
      POSTGRES_USER: root
    volumes:
      - ../pgdata:/var/lib/postgresql/data

  nest-pg-db-adminer:
    image: adminer
    container_name: nest-pg-adminer
    links:
      - nest-db:db
    ports:
      - 7000:8080

networks:
  default:
